--Lien qui permet l'installation du bordel : https://www.reddit.com/r/vimporn/comments/128zkpk/radioactive_harpoon/
---@module "radium_dark" A radioactive colorscheme.
---@author dharmx | https://github.com/dharmx
---@license GPL-3.0

-- GNU GENERAL PUBLIC LICENSE
-- Version 3, 29 June 2007
--
-- Permissions of this strong copyleft license are conditioned on
-- making available complete source code of licensed works and
-- modifications, which include larger works using a licensed work,
-- under the same license. Copyright and license notices must be
-- preserved. Contributors provide an express grant of patent rights.
--
-- Read the complete license here: https://www.gnu.org/licenses/gpl-3.0.en.html

-- THIS FILE IS AUTO-GENERATED!

vim.g.colors_name = "radium_dark"
vim.o.background = "dark"
local function HL(name, val) vim.api.nvim_set_hl(0, name, val) end

HL("@boolean", { bold = true, foreground = "#F87070" })
HL("@character", { foreground = "#E1C58D" })
-- HL("@comment", {  foreground = "#515C68"})
-- Les couleurs precedentes sont justes au dessus mais je ne vois rien, et en fait  ce sont les couleurs pour tous les commentaires mais j'ai change cela a l'aide
-- d'une substitution sur tout le fichier
HL("@comment", { foreground = "#E4DCCF" })
HL("@conditional", { foreground = "#F87070" })
HL("@constant", { bold = true, foreground = "#FF6666" })
HL("@constant.builtin", { bold = true, foreground = "#FFDF85" })
HL("@constant.macro", { foreground = "#E37070" })
HL("@constructor", { foreground = "#5FB0FC" })
HL("@debug", { foreground = "#7AAFC5" })
HL("@define", { foreground = "#C397D8" })
HL("@exception", { foreground = "#36C692" })
HL("@field", { foreground = "#36C692" })
HL("@float", { foreground = "#F3A4F1" })
HL("@function", { foreground = "#BE8FD7" })
HL("@function.builtin", { bold = true, foreground = "#36C692" })
HL("@function.macro", { foreground = "#FF7070" })
HL("@include", { bold = true, foreground = "#6AA6DF" })
HL("@keyword", { foreground = "#66B3FF" })
HL("@keyword.function", { foreground = "#FB7373" })
HL("@keyword.operator", { foreground = "#70C0BA" })
HL("@keyword.return", { foreground = "#66B3FF" })
HL("@label", { foreground = "#F87070" })
HL("@lua.constant.cmd", { bold = true, foreground = "#60B0FC" })
HL("@lua.constant.vim", { bold = true, foreground = "#FF6666" })
HL("@lua.function.pcall", { bold = true, foreground = "#F98989" })
HL("@lua.parameter.self", { bold = true, foreground = "#FFCE66" })
HL("@macro", { foreground = "#F98989" })
HL("@method", { foreground = "#B77EE0" })
HL("@namespace", { foreground = "#60B0FC" })
HL("@number", { foreground = "#54CED6" })
HL("@operator", { foreground = "#70C0BA" })
HL("@parameter", { foreground = "#FFE49D" })
HL("@preproc", { foreground = "#F96262" })
HL("@property", { foreground = "#54CED6" })
HL("@punctuation", { foreground = "#7AB0DF" })
HL("@punctuation.bracket", { foreground = "#FF7D7D" })
HL("@punctuation.delimiter", { foreground = "#7AB0DF" })
HL("@repeat", { foreground = "#B77EE0" })
HL("@storageclass", { foreground = "#F75858" })
HL("@string", { foreground = "#79DCAA" })
HL("@string.escape", { foreground = "#E5E49D" })
HL("@string.regex", { foreground = "#FFE390" })
HL("@string.special", { foreground = "#FCCF67" })
HL("@structure", { foreground = "#5FB0FC" })
HL("@tag", { foreground = "#7AB0DF" })
HL("@text", { foreground = "#D4D4D5" })
HL("@text.literal", { foreground = "#79CFAA" })
HL("@text.reference", { foreground = "#7AB0DF" })
HL("@text.title", { bold = true, foreground = "#FA6969" })
HL("@text.todo", { foreground = "#FFE59E" })
HL("@text.underline", { underline = true })
HL("@text.uri", { foreground = "#70C0BA", underline = true })
HL("@type", { foreground = "#F87070" })
HL("@type.definition", { foreground = "#C397D8" })
HL("@variable", { foreground = "#D4D4D5" })
HL("AlphaButtonLabelText", { foreground = "#FFE59E" })
HL("AlphaFooting", { bold = true, foreground = "#C397D8" })
HL("AlphaHeading", { foreground = "#1A1F25" })
HL("AlphaKeyPrefix", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("AlphaLoaded", { foreground = "#24292F" })
HL("AlphaScroll", { foreground = "#C397D8" })
HL("Bold", { bold = true })
HL("BookmarkAnnotationLine", { foreground = "#DDB1F2" })
HL("BookmarkAnnotationSign", { foreground = "#C397D8" })
HL("BookmarkLine", { background = "#31363B" })
HL("BookmarkSign", { foreground = "#F87070" })
HL("Boolean", { bold = true, foreground = "#F87070" })
HL("BufferLineBackground", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineBuffer", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineBufferSelected", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("BufferLineBufferVisible", { background = "#14171E", foreground = "#7AB0DF" })
HL("BufferLineCloseButton", { background = "#14171E", foreground = "#F87070" })
HL("BufferLineCloseButtonVisible", { background = "#14171E", foreground = "#F87070" })
HL("BufferLineDuplicate", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineDuplicateSelected", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineDuplicateVisible", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineFill", { background = "#101317", foreground = "#313743" })
HL("BufferLineIndicatorSelected", { background = "#7AB0DF", foreground = "#7AB0DF" })
HL("BufferLineIndicatorVisible", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineModified", { background = "#14171E", foreground = "#79DCAA" })
HL("BufferLineModifiedSelected", { background = "#7AB0DF", foreground = "#101317" })
HL("BufferLineModifiedVisible", { background = "#14171E", foreground = "#79DCAA" })
HL("BufferLineOffsetSeparator", { background = "#7AB0DF", foreground = "#7AB0DF" })
HL("BufferLinePick", { background = "#14171E", bold = true, foreground = "#D997C8" })
HL("BufferLinePickSelected", { background = "#7AB0DF", bold = true, foreground = "#E6CFA1" })
HL("BufferLinePickVisible", { background = "#14171E", bold = true, foreground = "#FCCF67" })
HL("BufferLineSeparator", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineSeparatorSelected", { background = "#7AB0DF", foreground = "#7AB0DF" })
HL("BufferLineSeparatorVisible", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineTab", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineTabClose", { background = "#101317", foreground = "#F87070" })
HL("BufferLineTabSelected", { background = "#101317", bold = true, foreground = "#7AB0DF" })
HL("BufferLineTabSeparator", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineTabSeparatorSelected", { foreground = "#101317" })
HL("BufferLinecloseButtonSelected", { background = "#7AB0DF", foreground = "#101317" })
HL("Character", { foreground = "#E1C58D" })
HL("CmpItemAbbr", { foreground = "#BABABE" })
HL("CmpItemAbbrDeprecated", { foreground = "#3E4450" })
HL("CmpItemAbbrMatch", { foreground = "#79DCAA" })
HL("CmpItemAbbrMatchFuzzy", { foreground = "#FCCF67" })
HL("CmpItemKind", { foreground = "#3E4450" })
HL("CmpItemKindClass", { foreground = "#F87070" })
HL("CmpItemKindColor", { foreground = "#7AB0DF" })
HL("CmpItemKindConstant", { foreground = "#FF6666" })
HL("CmpItemKindConstructor", { foreground = "#5FB0FC" })
HL("CmpItemKindEnum", { foreground = "#54CED6" })
HL("CmpItemKindEnumMember", { foreground = "#C297B9" })
HL("CmpItemKindEvent", { foreground = "#7AAFF3" })
HL("CmpItemKindField", { foreground = "#FFE69F" })
HL("CmpItemKindFile", { foreground = "#FCCF67" })
HL("CmpItemKindFolder", { foreground = "#FCCF67" })
HL("CmpItemKindFunction", { foreground = "#BE8FD7" })
HL("CmpItemKindInterface", { foreground = "#C397D8" })
HL("CmpItemKindKeyword", { foreground = "#66B3FF" })
HL("CmpItemKindMethod", { foreground = "#DC7272" })
HL("CmpItemKindModule", { foreground = "#5FB0FC" })
HL("CmpItemKindOperator", { foreground = "#70C0BA" })
HL("CmpItemKindProperty", { foreground = "#54CED6" })
HL("CmpItemKindReference", { foreground = "#FB7373" })
HL("CmpItemKindSnippet", { foreground = "#FFE59E" })
HL("CmpItemKindStruct", { foreground = "#5FB0FC" })
HL("CmpItemKindText", { foreground = "#5FB0FC" })
HL("CmpItemKindTypeParameter", { foreground = "#FFE49D" })
HL("CmpItemKindUnit", { foreground = "#54CED6" })
HL("CmpItemKindValue", { foreground = "#79DCAA" })
HL("CmpItemKindVariable", { foreground = "#36C692" })
HL("CmpItemMenu", { foreground = "#7AB0DF" })
HL("ColorColumn", { background = "#111419", foreground = "#171A20" })
HL("Comment", { foreground = "#E4DCCF" })
HL("Conceal", { foreground = "#353E47" })
HL("Conditional", { foreground = "#F87070" })
HL("Constant", { foreground = "#FF6666" })
HL("Cursor", { background = "#DFC184", foreground = "#101317" })
HL("CursorColumn", { background = "#191D21" })
HL("CursorLine", { background = "#191D21" })
HL("CursorLineFold", { background = "#101317", foreground = "#70C0BA" })
HL("CursorLineNr", { bold = true, foreground = "#FFE59E" })
HL("CursorLineSign", { background = "#101317" })
HL("Debug", { foreground = "#FB7373" })
HL("Decorator", { foreground = "#FFE59E" })
HL("Define", { foreground = "#C397D8" })
HL("Delimeter", { foreground = "#7AB0DF" })
HL("Delimiter", { foreground = "#FB7373" })
HL("DiagnosticError", { foreground = "#F87070" })
HL("DiagnosticFloatingError", { foreground = "#F87070" })
HL("DiagnosticFloatingHint", { foreground = "#C397D8" })
HL("DiagnosticFloatingInfo", { foreground = "#7AB0DF" })
HL("DiagnosticFloatingWarn", { foreground = "#F97F7F" })
HL("DiagnosticHint", { foreground = "#C397D8" })
HL("DiagnosticInfo", { foreground = "#7AB0DF" })
HL("DiagnosticSignError", { foreground = "#FB7373" })
HL("DiagnosticSignHint", { foreground = "#C397D8" })
HL("DiagnosticSignInfo", { foreground = "#7AB0DF" })
HL("DiagnosticSignWarn", { foreground = "#F97F7F" })
HL("DiagnosticUnderlineError", { foreground = "#F87070" })
HL("DiagnosticUnderlineHint", { foreground = "#C397D8" })
HL("DiagnosticUnderlineInfo", { foreground = "#7AB0DF" })
HL("DiagnosticUnderlineWarn", { foreground = "#F97F7F" })
HL("DiagnosticVirtualTextError", { foreground = "#F87070" })
HL("DiagnosticVirtualTextHint", { foreground = "#C397D8" })
HL("DiagnosticVirtualTextInfo", { foreground = "#7AB0DF" })
HL("DiagnosticVirtualTextWarn", { foreground = "#F97F7F" })
HL("DiagnosticWarn", { foreground = "#F97F7F" })
HL("DiffAdd", { foreground = "#79DCAA", reverse = true })
HL("DiffChange", { foreground = "#C397D8", reverse = true })
HL("DiffDelete", { foreground = "#F87070", reverse = true })
HL("DiffText", { foreground = "#7AB0DF", reverse = true })
HL("DiffviewCursorLine", { background = "#191D21" })
HL("DiffviewDiffAddAsDelete", { foreground = "#F87070", reverse = true })
HL("DiffviewDiffDelete", { foreground = "#E4DCCF" })
HL("DiffviewDim1", { foreground = "#E4DCCF" })
HL("DiffviewEndOfBuffer", { foreground = "#C397D8" })
HL("DiffviewFilePanelConflicts", { foreground = "#F97F7F" })
HL("DiffviewFilePanelCounter", { bold = true, foreground = "#36C692" })
HL("DiffviewFilePanelFileName", { foreground = "#D4D4D5" })
HL("DiffviewFilePanelPath", { foreground = "#E4DCCF" })
HL("DiffviewFilePanelRootPath", { bold = true, foreground = "#F87070" })
HL("DiffviewFilePanelSelected", { foreground = "#F87070" })
HL("DiffviewFilePanelTitle", { bold = true, foreground = "#F87070" })
HL("DiffviewFolderName", { foreground = "#FFE59E" })
HL("DiffviewFolderSign", { foreground = "#F96262" })
HL("DiffviewNonText", { foreground = "#222931" })
HL("DiffviewNormal", { background = "#101317", foreground = "#D4D4D5" })
HL("DiffviewPrimary", { foreground = "#BE8FD7" })
HL("DiffviewReference", { foreground = "#BE8FD7" })
HL("DiffviewSecondary", { foreground = "#79DCAA" })
HL("DiffviewSignColumn", { background = "#101317", foreground = "#D4D4D5" })
HL("DiffviewStatusIgnored", { foreground = "#E4DCCF" })
HL("DiffviewStatusLine", { background = "#101317", foreground = "#7AB0DF" })
HL("DiffviewStatusLineNC", { foreground = "#7AB0DF" })
HL("DiffviewWinSeparator", { foreground = "#171C21" })
HL("Directory", { foreground = "#FFE59E" })
HL("EndOfBuffer", { foreground = "#C397D8" })
HL("Error", { foreground = "#F76262" })
HL("ErrorMsg", { foreground = "#F87070" })
HL("Exception", { foreground = "#36C692" })
HL("FidgetTask", { foreground = "#1A1E27" })
HL("FidgetTitle", { bold = true, foreground = "#36C692" })
HL("Float", { foreground = "#F3A4F1" })
HL("FloatBorder", { background = "#151A1F", foreground = "#151A1F" })
HL("FloatShadow", { background = "#000000", blend = 80 })
HL("FloatShadowThrough", { background = "#000000", blend = 100 })
HL("FocusedSymbol", { background = "#666666", foreground = "#FFA0A0" })
HL("FoldColumn", { background = "#101317", foreground = "#70C0BA" })
HL("Folded", { background = "#101317", foreground = "#282F3C" })
HL("Function", { foreground = "#BE8FD7" })
HL("GitSignsAdd", { foreground = "#7AB0DF" })
HL("GitSignsAddInline", { reverse = true })
HL("GitSignsAddLn", { foreground = "#7AB0DF" })
HL("GitSignsAddLnInline", { reverse = true })
HL("GitSignsAddNr", { foreground = "#5FB0FC" })
HL("GitSignsAddPreview", { foreground = "#79DCAA", reverse = true })
HL("GitSignsChange", { foreground = "#21272D" })
HL("GitSignsChangeInline", { reverse = true })
HL("GitSignsChangeLn", { foreground = "#CB9FE0" })
HL("GitSignsChangeLnInline", { reverse = true })
HL("GitSignsChangeNr", { foreground = "#B77EE0" })
HL("GitSignsChangedelete", { foreground = "#21272D" })
HL("GitSignsChangedeleteLn", { foreground = "#CB9FE0" })
HL("GitSignsChangedeleteNr", { foreground = "#B77EE0" })
HL("GitSignsCurrentLineBlame", { foreground = "#222931" })
HL("GitSignsDelete", { foreground = "#FB7373" })
HL("GitSignsDeleteInline", { reverse = true })
HL("GitSignsDeleteLn", { foreground = "#F87070" })
HL("GitSignsDeleteLnInline", { reverse = true })
HL("GitSignsDeleteNr", { foreground = "#FE7676" })
HL("GitSignsDeletePreview", { foreground = "#F87070", reverse = true })
HL("GitSignsDeleteVirtLn", { foreground = "#F87070", reverse = true })
HL("GitSignsDeleteVirtLnInLine", { reverse = true })
HL("GitSignsStagedAdd", { foreground = "#3D586F" })
HL("GitSignsStagedAddLn", { foreground = "#3D586F" })
HL("GitSignsStagedAddNr", { foreground = "#2F587E" })
HL("GitSignsStagedChange", { foreground = "#101316" })
HL("GitSignsStagedChangeLn", { foreground = "#654F70" })
HL("GitSignsStagedChangeNr", { foreground = "#5B3F70" })
HL("GitSignsStagedChangedelete", { foreground = "#101316" })
HL("GitSignsStagedChangedeleteLn", { foreground = "#654F70" })
HL("GitSignsStagedChangedeleteNr", { foreground = "#5B3F70" })
HL("GitSignsStagedDelete", { foreground = "#7D3939" })
HL("GitSignsStagedDeleteLn", { foreground = "#7C3838" })
HL("GitSignsStagedDeleteNr", { foreground = "#7F3B3B" })
HL("GitSignsStagedTopdelete", { foreground = "#7D3939" })
HL("GitSignsStagedTopdeleteNr", { foreground = "#7F3B3B" })
HL("GitSignsTopdelete", { foreground = "#FB7373" })
HL("GitSignsTopdeleteNr", { foreground = "#FE7676" })
HL("GitSignsUntracked", { foreground = "#7AB0DF" })
HL("GitSignsUntrackedLn", { foreground = "#7AB0DF" })
HL("GitSignsUntrackedNr", { foreground = "#5FB0FC" })
HL("HarpoonBorder", { background = "#151A1F", foreground = "#151A1F" })
HL("HarpoonCurrentFile", { bold = true, foreground = "#FFE59E" })
HL("HarpoonCursor", { background = "#1A1F25", foreground = "#7AB0DF" })
HL("HarpoonTitle", { background = "#F87070", foreground = "#171C21" })
HL("HarpoonWindow", { background = "#151A1F", foreground = "#BABABE" })
HL("HighlightUrl", { foreground = "#70C0BA", underline = true })
HL("HlSearchFloat", { background = "#1A1E27", foreground = "#D0A4E5" })
HL("HlSearchLens", { background = "#1A1E27", foreground = "#87BDEC" })
HL("HlSearchLensNear", { background = "#FFE28F", bold = true, foreground = "#101317" })
HL("HlSearchNear", { background = "#1A1E27", bold = true, foreground = "#7DCDC7" })
HL("Identifier", { foreground = "#36C692" })
HL("IncSearch", { background = "#70C0BA", foreground = "#101317" })
HL("InclineBG", { background = "#171C21" })
HL("InclineBGNC", { background = "#14171E" })
HL("InclineCursorLine", { background = "#151A1F" })
HL("InclineCursorLineNC", { background = "#141A1D" })
HL("InclineFG", { foreground = "#D4D4D5" })
HL("InclineFGNC", { foreground = "#C397D8" })
HL("InclineNormal", { background = "#151A1F", foreground = "#BABABE" })
HL("InclineNormalNC", { background = "#151A1F", foreground = "#BABABE" })
HL("InclineThemeBG", { background = "#FFE59E" })
HL("Include", { bold = true, foreground = "#6AA6DF" })
HL("IndentBlanklineChar", { foreground = "#22272C" })
HL("IndentBlanklineContextChar", { foreground = "#7AB0DF" })
HL("IndentBlanklineContextStart", { background = "#16191F" })
HL("Italic", { italic = true })
HL("JaqBorder", { background = "#161921" })
HL("JaqWin", { background = "#161921" })
HL("Keyword", { foreground = "#66B3FF" })
HL("Label", { foreground = "#F87070" })
HL("LightBulbFloatWin", { foreground = "#FCCF67" })
HL("LightBulbSign", { foreground = "#FFE59E" })
HL("LightBulbVirtualText", { foreground = "#FFE59E" })
HL("LineNr", { foreground = "#BABABE" })
HL("LineNrAbove", { foreground = "#D4D4D5" })
HL("LineNrBelow", { foreground = "#D4D4D5" })
-- Les trois couleurs precedentes etaient de la forme du commentaire qui suit
-- HL("LineNrBelow", {  foreground = "#2E3645"})
HL("LspDiagnosticsSignError", { foreground = "#FB7373" })
HL("LspDiagnosticsSignHint", { foreground = "#C397D8" })
HL("LspDiagnosticsSignInfo", { foreground = "#7AB0DF" })
HL("LspDiagnosticsSignWarn", { foreground = "#FF7D7D" })
HL("LspReferenceRead", { background = "#161921", bold = true, foreground = "#82B8E7" })
HL("LspReferenceText", { background = "#161921", bold = true, foreground = "#CB9FE0" })
HL("LspReferenceWrite", { background = "#161921", bold = true, foreground = "#DC97CA" })
HL("LspSignatureActiveParameter", { background = "#161921", bold = true, foreground = "#78C8C2" })
HL("Macro", { foreground = "#F98989" })
HL("MatchBackground", { background = "#111419", foreground = "#171A20" })
HL("MatchParen", { background = "#202530", bold = true })
HL("MatchParenCur", { background = "#202530", bold = true })
HL("MatchWord", { background = "#202530", bold = true })
HL("ModeMsg", { bold = true, foreground = "#7AB0DF" })
HL("MonarkSelect", { foreground = "#54CED6" })
HL("MonarkTerminal", { foreground = "#54CED6" })
HL("MonarkVisualBlock", { foreground = "#FCCF67" })
HL("MonarkVisualLine", { foreground = "#F87070" })
HL("MoreMsg", { foreground = "#FFE59E" })
HL("MsgArea", { foreground = "#CACACD" })
HL("MsgSeparator", { foreground = "#C397D8" })
HL("NUICancel", { foreground = "#222931" })
HL("NUIHeading", { background = "#151A1F", foreground = "#F87070" })
HL("NUILine", { background = "#151A1F", foreground = "#22272C" })
HL("NUINo", { foreground = "#F87070" })
HL("NUINormal", { background = "#151A1F", foreground = "#151A1F" })
HL("NUIPrompt", { background = "#151A1F", foreground = "#7AB0DF" })
HL("NUIText", { background = "#151A1F", foreground = "#BABABE" })
HL("NUIYes", { foreground = "#7AB0DF" })
HL("NavicIconsArray", { foreground = "#FCCF67" })
HL("NavicIconsBoolean", { bold = true, foreground = "#F87070" })
HL("NavicIconsClass", { foreground = "#F75858" })
HL("NavicIconsConstant", { bold = true, foreground = "#FF6666" })
HL("NavicIconsConstructor", { foreground = "#5FB0FC" })
HL("NavicIconsEnum", { foreground = "#7AB0DF" })
HL("NavicIconsEnumMember", { foreground = "#F96262" })
HL("NavicIconsEvent", { foreground = "#79CFAA" })
HL("NavicIconsField", { foreground = "#36C692" })
HL("NavicIconsFile", { foreground = "#FFE59E" })
HL("NavicIconsFunction", { foreground = "#BE8FD7" })
HL("NavicIconsInterface", { foreground = "#FF7070" })
HL("NavicIconsKey", { foreground = "#F87070" })
HL("NavicIconsMethod", { foreground = "#B77EE0" })
HL("NavicIconsModule", { foreground = "#F98989" })
HL("NavicIconsNull", { bold = true, foreground = "#FFDF85" })
HL("NavicIconsNumber", { foreground = "#54CED6" })
HL("NavicIconsObject", { foreground = "#FFE390" })
HL("NavicIconsOperator", { foreground = "#70C0BA" })
HL("NavicIconsPackage", { bold = true, foreground = "#6AA6DF" })
HL("NavicIconsProperty", { foreground = "#54CED6" })
HL("NavicIconsString", { foreground = "#79DCAA" })
HL("NavicIconsStruct", { foreground = "#5FB0FC" })
HL("NavicIconsTypeParameter", { foreground = "#FFE49D" })
HL("NavicIconsVariable", { bold = true, foreground = "#FA6969" })
HL("NavicSeparator", { foreground = "#7AB0DF" })
HL("NavicText", { foreground = "#AAAAAF" })
HL("NeogitBranch", { bold = true, foreground = "#36C692" })
HL("NeogitCommitViewHeader", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("NeogitDiffAdd", { background = "#16191D", foreground = "#7AB0DF" })
HL("NeogitDiffContextHighlight", { background = "#1A1D24" })
HL("NeogitDiffDelete", { background = "#1C1F22", foreground = "#F87070" })
HL("NeogitFilePath", { foreground = "#70C0BA" })
HL("NeogitFold", { foreground = "#54CED6" })
HL("NeogitHunkHeader", { background = "#171C21", foreground = "#FFE59E" })
HL("NeogitHunkHeaderHighlight", { background = "#FFE59E", foreground = "#101317" })
HL("NeogitNotificationError", { background = "#101317", foreground = "#F87070" })
HL("NeogitNotificationInfo", { background = "#101317", foreground = "#7AB0DF" })
HL("NeogitNotificationWarning", { background = "#101317", foreground = "#FFE59E" })
HL("NeogitObjectId", { foreground = "#C397D8" })
HL("NeogitRebaseDone", { bold = true, foreground = "#79DCAA" })
HL("NeogitRebasing", { bold = true, foreground = "#FFE59E" })
HL("NeogitRecentcommits", { bold = true, foreground = "#79DCAA" })
HL("NeogitRemote", { bold = true, foreground = "#FCCF67" })
HL("NeogitStagedchanges", { bold = true, foreground = "#FFE59E" })
HL("NeogitStash", { foreground = "#70C0BA" })
HL("NeogitStashes", { bold = true, foreground = "#70C0BA" })
HL("NeogitUnmergedInto", { foreground = "#7AB0DF" })
HL("NeogitUnmergedchanges", { bold = true, foreground = "#36C692" })
HL("NeogitUnpulledFrom", { foreground = "#54CED6" })
HL("NeogitUnpulledchanges", { bold = true, foreground = "#54CED6" })
HL("NeogitUnstagedchanges", { bold = true, foreground = "#FB7373" })
HL("NeogitUntrackedfiles", { bold = true, foreground = "#5FB0FC" })
HL("NonText", { foreground = "#222931" })
HL("Normal", { background = "#101317", foreground = "#D4D4D5" })
HL("NormalFloat", { background = "#151A1F", foreground = "#BABABE" })
HL("NotifyBackground", { background = "#101317", foreground = "#D4D4D5" })
HL("NotifyDEBUGBody", { background = "#171C21", foreground = "#C397D8" })
HL("NotifyDEBUGBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyDEBUGIcon", { background = "#171C21", foreground = "#B77EE0" })
HL("NotifyDEBUGTitle", { background = "#171C21", foreground = "#C397D8" })
HL("NotifyERRORBody", { background = "#171C21", foreground = "#F87070" })
HL("NotifyERRORBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyERRORIcon", { background = "#171C21", foreground = "#FB7373" })
HL("NotifyERRORTitle", { background = "#171C21", foreground = "#F87070" })
HL("NotifyINFOBody", { background = "#171C21", foreground = "#7AB0DF" })
HL("NotifyINFOBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyINFOIcon", { background = "#171C21", foreground = "#5FB0FC" })
HL("NotifyINFOTitle", { background = "#171C21", foreground = "#7AB0DF" })
HL("NotifyLogTime", { foreground = "#E4DCCF" })
HL("NotifyLogTitle", { foreground = "#FB7373" })
HL("NotifyTRACEBody", { background = "#171C21", foreground = "#79DCAA" })
HL("NotifyTRACEBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyTRACEIcon", { background = "#171C21", foreground = "#36C692" })
HL("NotifyTRACETitle", { background = "#171C21", foreground = "#79DCAA" })
HL("NotifyWARNBody", { background = "#171C21", foreground = "#FFE59E" })
HL("NotifyWARNBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyWARNIcon", { background = "#171C21", foreground = "#FCCF67" })
HL("NotifyWARNTitle", { background = "#171C21", foreground = "#FFE59E" })
HL("Number", { foreground = "#54CED6" })
HL("NvimTreeBookmark", { foreground = "#FFE59E" })
HL("NvimTreeClosedFolderIcon", { foreground = "#B77EE0" })
HL("NvimTreeCursorLine", { foreground = "#12151B" })
HL("NvimTreeCursorLineNr", { bold = true, foreground = "#36C692" })
HL("NvimTreeEmptyFolderName", { foreground = "#B58ED1" })
HL("NvimTreeExecFile", { foreground = "#D997C8" })
HL("NvimTreeFileDeleted", { foreground = "#FB7373" })
HL("NvimTreeFileDirty", { foreground = "#70C0BA" })
HL("NvimTreeFileIgnored", { foreground = "#171C21" })
HL("NvimTreeFileMerge", { foreground = "#36C692" })
HL("NvimTreeFileNew", { foreground = "#FFE59E" })
HL("NvimTreeFileRenamed", { foreground = "#5FB0FC" })
HL("NvimTreeFileStaged", { foreground = "#D997C8" })
HL("NvimTreeFolderIcon", { foreground = "#B77EE0" })
HL("NvimTreeFolderName", { foreground = "#B77EE0" })
HL("NvimTreeGitDeleted", { foreground = "#F87070" })
HL("NvimTreeGitDirty", { foreground = "#70C0BA" })
HL("NvimTreeGitIgnored", { foreground = "#171C21" })
HL("NvimTreeGitMerge", { foreground = "#54CED6" })
HL("NvimTreeGitNew", { foreground = "#FFE59E" })
HL("NvimTreeGitRenamed", { foreground = "#5FB0FC" })
HL("NvimTreeGitStaged", { foreground = "#D997C8" })
HL("NvimTreeImageFile", { foreground = "#B77EE0" })
HL("NvimTreeIndentMarker", { foreground = "#1D2529" })
HL("NvimTreeNormal", { background = "#0C0E11", foreground = "#BABABE" })
HL("NvimTreeNormalNC", { background = "#0C0E11", foreground = "#BABABE" })
HL("NvimTreePopup", { foreground = "#7AB0DF" })
HL("NvimTreeRootFolder", { bold = true, foreground = "#F87070" })
HL("NvimTreeSymlink", { foreground = "#70C0BA" })
HL("NvimTreeVertSplit", { background = "#0C0E11", foreground = "#0C0E11" })
HL("NvimTreeWinSeparator", { background = "#0C0E11", foreground = "#0C0E11" })
HL("NvimTreeWindowPicker", { background = "#191C24", foreground = "#7AB0DF" })
HL("NvimUnaryMinus", { foreground = "#70C0BA" })
HL("NvimUnaryOperator", { foreground = "#70C0BA" })
HL("NvimUnaryPlus", { foreground = "#70C0BA" })
HL("Operator", { foreground = "#70C0BA" })
HL("Pmenu", { background = "#171D20", foreground = "#A0A0A5" })
HL("PmenuSbar", { background = "#171D20", foreground = "#A0A0A5" })
HL("PmenuSel", { background = "#1B2226", foreground = "#ADADB2" })
HL("PmenuThumb", { background = "#1E2225" })
HL("PreCondit", { foreground = "#F96262" })
HL("PreProc", { foreground = "#F96262" })
HL("Question", { foreground = "#79DCAA" })
HL("QuickFixLine", { background = "#FFE59E", foreground = "#101317" })
HL("RedrawDebugClear", { background = "#FFFF00" })
HL("RedrawDebugComposed", { background = "#008000" })
HL("RedrawDebugNormal", { reverse = true })
HL("RedrawDebugRecompose", { background = "#FF0000" })
HL("Repeat", { foreground = "#B77EE0" })
HL("RnvimrCurses", { background = "#101317", foreground = "#D4D4D5" })
HL("RnvimrNormal", { background = "#151A1F", foreground = "#BABABE" })
HL("ScrollbarCursor", { foreground = "#54CED6" })
HL("ScrollbarCursorHandle", { background = "#20272E", foreground = "#54CED6" })
HL("ScrollbarError", { foreground = "#F87070" })
HL("ScrollbarErrorHandle", { foreground = "#F87070" })
HL("ScrollbarGitAdd", { foreground = "#7AB0DF" })
HL("ScrollbarGitAddHandle", { foreground = "#82B8E7" })
HL("ScrollbarGitChange", { foreground = "#C397D8" })
HL("ScrollbarGitChangeHandle", { foreground = "#BD84E6" })
HL("ScrollbarGitDelete", { foreground = "#F87070" })
HL("ScrollbarGitDeleteHandle", { foreground = "#FF7B7B" })
HL("ScrollbarHandle", { foreground = "#7AB0DF" })
HL("ScrollbarHint", { foreground = "#C397D8" })
HL("ScrollbarHintHandle", { foreground = "#B77EE0" })
HL("ScrollbarInfo", { foreground = "#7AB0DF" })
HL("ScrollbarInfoHandle", { foreground = "#7AB0DF" })
HL("ScrollbarMisc", { foreground = "#DC97CA" })
HL("ScrollbarMiscHandle", { foreground = "#70C0BA" })
HL("ScrollbarSearch", { foreground = "#FFE59E" })
HL("ScrollbarSearchHandle", { foreground = "#FFD76F" })
HL("ScrollbarWarn", { foreground = "#F97F7F" })
HL("ScrollbarWarnHandle", { foreground = "#FA6969" })
HL("Search", { background = "#FFE59E", foreground = "#101317" })
HL("SignColumn", { background = "#101317" })
HL("Special", { foreground = "#FB7373" })
HL("SpecialChar", { foreground = "#C397D8" })
HL("SpecialComment", { foreground = "#FFDF8F" })
HL("SpecialKey", { bold = true, foreground = "#FFE59E" })
HL("SpellBad", { foreground = "#F87070" })
HL("SpellCap", { foreground = "#FCCF67" })
HL("SpellLocal", { foreground = "#FB7373" })
HL("SpellRare", { foreground = "#54CED6" })
HL("Statement", { foreground = "#F87070" })
HL("StatusLine", { background = "#101317", foreground = "#7AB0DF" })
HL("StatusLineNC", { foreground = "#7AB0DF" })
HL("StorageClass", { foreground = "#F75858" })
HL("String", { foreground = "#79DCAA" })
HL("Structure", { foreground = "#5FB0FC" })
HL("Substitute", { background = "#B77EE0", foreground = "#101317" })
HL("TabLine", { background = "#101317", bold = true, foreground = "#2C3640" })
HL("TabLineFill", { background = "#101317", foreground = "#7AB0DF" })
HL("TabLineSel", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("Tag", { foreground = "#7AB0DF" })
HL("TelescopeMatching", { bold = true, foreground = "#DC97CA" })
HL("TelescopePreviewBorder", { background = "#0E1014", foreground = "#0E1014" })
HL("TelescopePreviewLine", { background = "#15181E" })
HL("TelescopePreviewNormal", { background = "#0E1014", foreground = "#BABABE" })
HL("TelescopePreviewTitle", { background = "#7AB0DF", foreground = "#101317" })
HL("TelescopePromptBorder", { background = "#12151B", foreground = "#14191D" })
HL("TelescopePromptCounter", { background = "#12151B", bold = true, foreground = "#D997C8" })
HL("TelescopePromptNormal", { background = "#12151B", foreground = "#BABABE" })
HL("TelescopePromptPrefix", { background = "#12151B", foreground = "#F87070" })
HL("TelescopePromptTitle", { background = "#F87070", foreground = "#101317" })
HL("TelescopeResultsBorder", { background = "#0C0E11", foreground = "#0C0E11" })
HL("TelescopeResultsNormal", { background = "#0C0E11", foreground = "#BABABE" })
HL("TelescopeResultsTitle", { background = "#79DCAA", foreground = "#101317" })
HL("TelescopeSelection", { background = "#101317", foreground = "#54CED6" })
HL("TelescopeSelectionCaret", { background = "#101317", foreground = "#FB7373" })
HL("TermCursor", { reverse = true })
HL("Title", { bold = true, foreground = "#4B5259" })
HL("Todo", { foreground = "#FFE59E" })
HL("TodoBgBUG", { background = "#F87070", bold = true, foreground = "#171C21" })
HL("TodoBgCHORE", { background = "#70C0BA", bold = true, foreground = "#171C21" })
HL("TodoBgCLEAN", { background = "#7AB0DF", bold = true, foreground = "#171C21" })
HL("TodoBgDEMO", { background = "#5FB0FC", bold = true, foreground = "#171C21" })
HL("TodoBgFIX", { background = "#FFE59E", bold = true, foreground = "#171C21" })
HL("TodoBgHACK", { background = "#79DCAA", bold = true, foreground = "#171C21" })
HL("TodoBgIMPROVE", { background = "#5FB0FC", bold = true, foreground = "#171C21" })
HL("TodoBgNOTE", { background = "#36C692", bold = true, foreground = "#171C21" })
HL("TodoBgPERF", { background = "#FCCF67", bold = true, foreground = "#171C21" })
HL("TodoBgTEST", { background = "#54CED6", bold = true, foreground = "#171C21" })
HL("TodoBgTODO", { background = "#C397D8", bold = true, foreground = "#171C21" })
HL("TodoBgUPDATE", { background = "#B77EE0", bold = true, foreground = "#171C21" })
HL("TodoBgWANTS", { background = "#FFEDA6", bold = true, foreground = "#171C21" })
HL("TodoBgWARN", { background = "#E17272", bold = true, foreground = "#171C21" })
HL("TodoFgBUG", { foreground = "#F87070" })
HL("TodoFgCHORE", { foreground = "#70C0BA" })
HL("TodoFgCLEAN", { foreground = "#7AB0DF" })
HL("TodoFgDEMO", { foreground = "#5FB0FC" })
HL("TodoFgFIX", { foreground = "#FFE59E" })
HL("TodoFgHACK", { foreground = "#79DCAA" })
HL("TodoFgIMPROVE", { foreground = "#5FB0FC" })
HL("TodoFgNOTE", { foreground = "#36C692" })
HL("TodoFgPERF", { foreground = "#FCCF67" })
HL("TodoFgTEST", { foreground = "#54CED6" })
HL("TodoFgTODO", { foreground = "#C397D8" })
HL("TodoFgUPDATE", { foreground = "#B77EE0" })
HL("TodoFgWANTS", { foreground = "#FFEDA6" })
HL("TodoFgWARN", { foreground = "#E17272" })
HL("TodoSignBUG", { background = "#101317", foreground = "#F87070" })
HL("TodoSignCHORE", { background = "#101317", foreground = "#70C0BA" })
HL("TodoSignCLEAN", { background = "#101317", foreground = "#7AB0DF" })
HL("TodoSignDEMO", { background = "#101317", foreground = "#5FB0FC" })
HL("TodoSignFIX", { background = "#101317", foreground = "#FCCF67" })
HL("TodoSignHACK", { background = "#101317", foreground = "#79DCAA" })
HL("TodoSignIMPROVE", { background = "#101317", foreground = "#5FB0FC" })
HL("TodoSignNOTE", { background = "#101317", foreground = "#36C692" })
HL("TodoSignPERF", { background = "#101317", foreground = "#FCCF67" })
HL("TodoSignTEST", { background = "#101317", foreground = "#54CED6" })
HL("TodoSignTODO", { background = "#101317", foreground = "#C397D8" })
HL("TodoSignUPDATE", { background = "#101317", foreground = "#B77EE0" })
HL("TodoSignWANTS", { background = "#101317", foreground = "#FFEDA6" })
HL("TodoSignWARN", { background = "#101317", foreground = "#E17272" })
HL("ToggleTerm1FloatBorder", { background = "#151A1F", foreground = "#151A1F" })
HL("ToggleTerm1NormalFloat", { background = "#151A1F", foreground = "#BABABE" })
HL("TreesitterContext", { background = "#171A20" })
HL("TroubleNormal", { background = "#0C0E11" })
HL("Type", { foreground = "#F87070" })
HL("Typedef", { foreground = "#C397D8" })
HL("Underlined", { underline = true })
HL("UndotreeBranch", { foreground = "#FF6666" })
HL("UndotreeCurrent", { foreground = "#F87070" })
HL("UndotreeFirstNode", { foreground = "#BE8FD7" })
HL("UndotreeHead", { foreground = "#36C692" })
HL("UndotreeHelp", { foreground = "#E4DCCF" })
HL("UndotreeHelpKey", { bold = true, foreground = "#F87070" })
HL("UndotreeHelpTitle", { foreground = "#F87070" })
HL("UndotreeNext", { foreground = "#7AB0DF" })
HL("UndotreeNode", { foreground = "#79DCAA" })
HL("UndotreeNodeCurrent", { foreground = "#E1C58D" })
HL("UndotreeSavedBig", { background = "#202530", bold = true })
HL("UndotreeSavedSmall", { foreground = "#FB7373" })
HL("UndotreeSeq", { foreground = "#E4DCCF" })
HL("UndotreeTimeStamp", { foreground = "#70C0BA" })
HL("VertSplit", { foreground = "#171C21" })
HL("VirtColumn", { background = "#101317", foreground = "#171A20" })
HL("Visual", { background = "#192023" })
HL("WarningMsg", { foreground = "#FB7373" })
HL("WhichKey", { foreground = "#C397D8" })
HL("WhichKeyBorder", { background = "#0E1014" })
HL("WhichKeyDesc", { foreground = "#FFE59E" })
HL("WhichKeyFloat", { background = "#0E1014" })
HL("WhichKeyGroup", { bold = true, foreground = "#F87070" })
HL("WhichKeySeparator", { foreground = "#7AB0DF" })
HL("WhichKeyValue", { foreground = "#929299" })
HL("Whitespace", { foreground = "#1E222A" })
HL("WildMenu", { background = "#7AB0DF", foreground = "#101317" })
HL("WinBar", { bold = true })
HL("WinBarNC", { bold = true })
HL("WinSeparator", { foreground = "#171C21" })
HL("luaComment", { foreground = "#E4DCCF" })
HL("luaCommentDelimiter", { foreground = "#E4DCCF" })
HL("luaCond", { foreground = "#F87070" })
HL("luaCondElse", { foreground = "#F87070" })
HL("luaConstant", { foreground = "#FF6666" })
HL("luaError", { foreground = "#F76262" })
HL("luaFor", { foreground = "#B77EE0" })
HL("luaFunc", { foreground = "#36C692" })
HL("luaFunction", { foreground = "#BE8FD7" })
HL("luaLabel", { foreground = "#F87070" })
HL("luaMetaMethod", { foreground = "#BE8FD7" })
HL("luaNumber", { foreground = "#54CED6" })
HL("luaOperator", { foreground = "#70C0BA" })
HL("luaParenError", { foreground = "#F76262" })
HL("luaRepeat", { foreground = "#B77EE0" })
HL("luaSpecial", { foreground = "#C397D8" })
HL("luaStatement", { foreground = "#F87070" })
HL("luaString", { foreground = "#79DCAA" })
HL("luaString2", { foreground = "#79DCAA" })
HL("luaStringDelimiter", { foreground = "#79DCAA" })
HL("luaSymbolOperator", { foreground = "#70C0BA" })
HL("luaTable", { foreground = "#5FB0FC" })
HL("luaTodo", { foreground = "#FFE59E" })
HL("monarkCommand", { foreground = "#5FB0FC" })
HL("monarkInsert", { foreground = "#7AB0DF" })
HL("monarkNormal", { foreground = "#79DCAA" })
HL("monarkReplace", { foreground = "#C397D8" })
HL("monarkVisual", { foreground = "#FFE59E" })
HL("rainbowcol1", { foreground = "#D098FF" })
HL("rainbowcol2", { foreground = "#79CAFF" })
HL("rainbowcol3", { foreground = "#94CAF9" })
HL("rainbowcol4", { foreground = "#50E0AC" })
HL("rainbowcol5", { foreground = "#FFE981" })
HL("rainbowcol6", { foreground = "#FF9393" })
HL("rainbowcol7", { foreground = "#FF8D8D" })
