-- return function()
local function remap()
    local dap = require("dap")
    local dapui = require("dapui")
    local map = require("utils.helpers").set_prefix("Debug")
    map("<leader>hR", dap.run_to_cursor, "[D]ebug [R]un to Cursor")
    map("<leader>hE", function() dapui.eval(vim.fn.input("[Expression] > ")) end, "[D]ebug[E]valuate Input")
    map("<leader>hC", function() dap.set_breakpoint(vim.fn.input("[Condition] > ")) end,
        "[D]ebug [C]onditional Breakpoint")
    map("<leader>hb", dap.step_back, "[D]ebug Step [B]ack")
    map("<leader>hc", dap.continue, "[D]ebug [C]ontinue")
    map("<leader>hd", dap.disconnect, "[D]ebug [D]isconnect")
    map("<leader>he", dapui.eval, "[D]ebug [E]valuate", { "n", "v" })
    map("<leader>hg", dap.session, "[D]ebug [G]et Session")
    map("<leader>hh", require("dap.ui.widgets").hover, "[D]ebug: [H]over Variables")
    map("<leader>hS", function() require("dap.ui.widgets").scopes() end, "[D]ebug [S]copes")
    map("<leader>hi", dap.step_into, "[D]ebug Step [I]nto")
    map("<leader>ho", dap.step_over, "[D]ebug Step [O]ver")
    map("<leader>hp", dap.pause, "[D]ebug [P]ause")
    map("<leader>hq", dap.close, "[D]ebug [Q]uit")
    -- map("<leader>hr", require("dap.repl").toggle, "[D]ebug Toggle [R]EPL")
    map("<leader>hr", dap.restart, "[D]ebug [R]estart")
    map("<leader>hs", dap.continue, "[D]ebug [S]tart debugger")
    map("<leader>ht", dap.toggle_breakpoint, "[D]ebug [T]oggle Breakpoint")
    map("<leader>hx", dap.terminate, "[D]ebug Terminate debug session")
    map("<leader>hu", dap.step_out, "[D]ebug Step O[u]t")
    map("<leader>hU", dapui.toggle, "[D]ebug Toggle [U]I")
    -- Toggle to see last session result. Without this, you can't see session output in case of unhandled exception.
    map("<F7>", dapui.toggle, "Debug: See last session result.")
end

remap()
