#!/usr/bin/env bash
# The one canonical theme-change flow. Given a base46 theme name, extracts
# its type + base_16 palette (without opening nvim's UI) and propagates it
# to nvim's persisted default, tmux, wezterm, herdr, waybar, and the sway
# wallpaper.
#
# Called from: nvim's Telescope theme picker, and the wofi global picker
# (pick-theme.sh). Both converge here so there's one propagation path.

set -euo pipefail

THEME_NAME="${1:?usage: set-theme.sh <base46-theme-name>}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_FILE="$HOME/.theme_state"
NVCONFIG="$HOME/.config/nvim/lua/nvconfig.lua"
WEZTERM_PALETTE="$HOME/.config/wezterm/nvim_palette.lua"
WEZTERM_CONFIG="$HOME/.config/wezterm/wezterm.lua"
HERDR_CONFIG="$HOME/.config/herdr/config.toml"

json="$(THEME_NAME="$THEME_NAME" nvim --headless --clean -u NONE \
    -c "lua package.path = package.path .. ';$HOME/.local/share/nvim/lazy/base46/lua/?.lua;$HOME/.local/share/nvim/lazy/base46/lua/?/init.lua;$HOME/.config/nvim/lua/?.lua'" \
    -c "luafile $SCRIPT_DIR/extract-palette.lua" 2>/dev/null)"

if [ -z "$json" ]; then
    echo "set-theme.sh: failed to extract palette for '$THEME_NAME'" >&2
    exit 1
fi

mode="$(echo "$json" | jq -r '.type')"
if [ "$mode" != "light" ] && [ "$mode" != "dark" ]; then
    echo "set-theme.sh: theme '$THEME_NAME' has no valid type field" >&2
    exit 1
fi

b() { echo "$json" | jq -r ".base16.$1"; }
base00="$(b base00)"; base01="$(b base01)"; base02="$(b base02)"; base03="$(b base03)"
base04="$(b base04)"; base05="$(b base05)"; base06="$(b base06)"; base07="$(b base07)"
base08="$(b base08)"; base09="$(b base09)"; base0A="$(b base0A)"; base0B="$(b base0B)"
base0C="$(b base0C)"; base0D="$(b base0D)"; base0E="$(b base0E)"; base0F="$(b base0F)"

# --- state ---
printf '%s' "$mode" >"$STATE_FILE"

# --- nvim: persist as default for future opens ---
# Anchored on the "-- default theme" comment so this only ever touches the
# M.base46.theme line, not the unrelated M.ui.statusline.theme field.
sed -i -E "s/^([[:space:]]*theme = \")[^\"]+(\", -- default theme)\$/\1${THEME_NAME}\2/" "$NVCONFIG"

# --- tmux: regenerate thm_* palette, standard base16 role mapping ---
cat >"$SCRIPT_DIR/tmux-palette.sh" <<EOF
thm_bg="${base00}"
thm_fg="${base05}"
thm_gray="${base02}"
thm_black4="${base03}"
thm_red="${base08}"
thm_orange="${base09}"
thm_yellow="${base0A}"
thm_green="${base0B}"
thm_cyan="${base0C}"
thm_blue="${base0D}"
thm_magenta="${base0E}"
thm_pink="${base0F}"
EOF
if command -v tmux >/dev/null 2>&1 && tmux info >/dev/null 2>&1; then
    bash "$SCRIPT_DIR/tmux-nvim-theme.sh"
fi

# --- wezterm: regenerate palette module, standard base16-to-ANSI mapping ---
cat >"$WEZTERM_PALETTE" <<EOF
-- Generated by set-theme.sh from the active nvim theme ($THEME_NAME). Do not edit by hand.
return {
	foreground = "${base05}",
	background = "${base00}",
	cursor_bg = "${base05}",
	cursor_fg = "${base00}",
	cursor_border = "${base05}",
	selection_fg = "${base00}",
	selection_bg = "${base05}",
	ansi = {
		"${base00}", "${base08}", "${base0B}", "${base0A}",
		"${base0D}", "${base0E}", "${base0C}", "${base05}",
	},
	brights = {
		"${base03}", "${base08}", "${base0B}", "${base0A}",
		"${base0D}", "${base0E}", "${base0C}", "${base07}",
	},
}
EOF
if [ -f "$WEZTERM_CONFIG" ]; then
    touch "$WEZTERM_CONFIG"
fi

# --- herdr: base theme name + the 4 documented custom overrides ---
if [ "$mode" = "light" ]; then
    herdr_theme="catppuccin-latte"
else
    herdr_theme="catppuccin"
fi
if [ -f "$HERDR_CONFIG" ]; then
    sed -i -E "s/^name = \"catppuccin(-latte)?\"/name = \"$herdr_theme\"/" "$HERDR_CONFIG"
    if ! grep -q '^\[theme\.custom\]' "$HERDR_CONFIG"; then
        printf '\n[theme.custom]\n' >>"$HERDR_CONFIG"
    fi
    python3 - "$HERDR_CONFIG" "$base01" "$base0F" "$base08" "$base0B" <<'PYEOF'
import re, sys
path, panel_bg, accent, red, green = sys.argv[1:6]
with open(path) as f:
    content = f.read()

def set_kv(content, key, value):
    pattern = re.compile(rf'^{key} = ".*"$', re.MULTILINE)
    line = f'{key} = "{value}"'
    if pattern.search(content):
        return pattern.sub(line, content, count=1)
    return content.replace("[theme.custom]", f"[theme.custom]\n{line}", 1)

content = set_kv(content, "panel_bg", panel_bg)
content = set_kv(content, "accent", accent)
content = set_kv(content, "red", red)
content = set_kv(content, "green", green)

with open(path, "w") as f:
    f.write(content)
PYEOF
    if pgrep -f "$HOME/.local/bin/herdr" >/dev/null 2>&1; then
        herdr server reload-config >/dev/null 2>&1 || true
    fi
fi

# --- waybar + wallpaper (coarse light/dark bucket) ---
"$SCRIPT_DIR/apply-theme.sh"
